#!/bin/sh -e

for patch in ./*.patch; do
    patch -p1 < "$patch"
done

cd ./src

./configure \
    WARN_CFLAGS= \
    --prefix="$1/usr" \
    --enable-shared \
    --disable-static \
    --disable-nls \
    --disable-rpath \
    --without-tcl

make -j1
make install
