#!/bin/sh -e

mkdir texbuild
cd texbuild

../configure -C \
	--prefix=/usr \
	--sysconfdir=/etc \
	--mandir=/usr/share/man \
	--infodir=/usr/share/info \
	--localstatedir=/var \
	--disable-xdvik

make
make DESTDIR="$1" install
