#!/bin/sh -e

patchelf --remove-needed libintl.so.8 ./chrome

cd ..
mkdir -p "$1/usr/lib"
mkdir -p "$1/usr/bin"

cp -R ungoogled*/ "$1/usr/lib/chromium"
ln -s /usr/lib/chromium/chrome "$1/usr/bin/chromium"
