#!/bin/sh -e

patch -p1 < ./1-meson.build.patch

export PKG_CONFIG_PATH="$PWD"
(
	cd libdbus-stub
	sed -i 's/FALSE/TRUE/g' dbus/dbus-syntax.c
	make
)

cp libdbus-stub/libdbus-1.so ./libdbus-1.so.1

cat <<EOF > dbus-1.pc
Name: dbus
Description: Free desktop message bus
Version: 1.13.18
Libs: -L$PWD -ldbus-1
Libs.private:
Cflags: -I$PWD/libdbus-stub
EOF

sh>/dev/tty

(
	cd at-spi2-core
	./as2cbuild
)
cp at-spi2-core/build/atspi/*.so ./

patchelf --remove-needed libintl.so.8 ./chrome
patchelf --replace-needed libdbus-1.so.3 libdbus-1.so.1 ./chrome

sh>/dev/tty

mkdir -p "$1/usr/lib"
mkdir -p "$1/usr/bin"

cp -R "$PWD" "$1/usr/lib/chromium"
ln -s /usr/lib/chromium/chrome "$1/usr/bin/chromium"
