#!/bin/sh

dest="$1/usr/share/xml/docbook/xsl-stylesheets-1.79.1"

install -dm755 "$dest"

install -m644 VERSION VERSION.xsl "$dest"/ || return 1

for dir in assembly common eclipse epub epub3 fo highlighting html \
	htmlhelp javahelp lib manpages params profiling roundtrip \
	template website xhtml xhtml-1_1 xhtml5; do

	install -dm755 "$dest/$dir"
	for f in $dir/*.xml $dir/*.xsl $dir/*.dtd $dir/*.ent; do
		[ -e "$f" ] || continue
		install -m644 $f "$dest/$dir" || return 1
	done
done

install -dm755 "$1/etc/xml" || return 1

install -m644 -D COPYING \
    "$1/usr/share/licenses/docbook-xsl/COPYING"
